- id: ksconf-check
  name: Ksconf Splunk CONF - Check syntax
  description: Check that all .conf files are syntactically valid
  entry: ksconf check -q
  language: python
  files: (\.conf|(local|default)\.meta)$

- id: ksconf-sort
  name: Ksconf Splunk CONF - Sort conf files
  description: Sort all stanzas and keys in .conf files.  Files can be skipped by adding a comment with KSCONF-NO-SORT
  entry: ksconf sort -i -q
  language: python
  files: (\.conf|(local|default)\.meta)$

- id: ksconf-xml-format
  name: Ksconf Splunk CONF - Normalize XML
  description: Normalize and apply consistent XML indentation and CDATA usage for XML dashboards and navigation files.
  entry: ksconf xml-format -q --disable-pre-commit-migration-check
  language: python
  files: data/ui/(views|nav)/[^/]+\.xml$
